---
format:
  html:
    toc: true
    toc-location: right
    number-sections: true
bibliography: references.json
csl: apa.csl
lang: de
---

# Übersicht {.unnumbered}

Dieses Buch untersucht, wie generative künstliche Intelligenz (GenAI) Lehre, Lernen und Forschung verändern kann. Es richtet sich an Lehrende, Forschende und Studierende, die verstehen möchten, **wie KI als Werkzeug der Hochschuldidaktik** eingesetzt werden kann.

Das Buch besteht aus den folgenden Kapiteln:

1.  Überblick: KI als Hilfe zum Lehren und Lernen\
2.  Grundbegriffe und technische Grundlagen\
3.  Didaktische Prinzipien und Cognitive Science\
4.  Praxisbeispiele: KI als Hiwi, Copilot, Tutor, Simulator\
5.  Empfehlungen zur Umsetzung \
6.  Appendix 01: Strukturierung der didaktischen Prompts \
7.  Appendix 02: Best-Practice Sammlung didaktischer Prompts und Aufgabenstellungen \


# Updates seit der Vorversion vom September 2025  {.unnumbered}

- Erstellung der interaktiven Online-Version.
- Mehrere interaktive Elemente und Lernspiele wurden in den ersten Kapiteln hinzugefügt. 
- Im Anhang finden Sie jetzt eine Vielzahl von Best Practice Beispielen für didaktische Prompts und integrierte Aufgabenstellungen von internationalen Hochschulen.
- Diese Beta-Version hat noch kleinere Bugs und Formatierungsfehler, die in den nächsten Monaten behoben werden. 
- Das nächste Update wird im Juni 2026 bei Logos als Open Access Lehrbuch publiziert werden.

# Didaktische Kurse 2026  {.unnumbered}

- Wer das Thema GenAI in der Lehre anwendungsorientiert vertiefen will, findet hier eine aktuelle **Übersicht der hochschuldidaktischen Kurse,** die ich im Netzwerk hdw anbiete: <https://www.hdw-nrw.de/workshops?referentensuche=Prof.%20Dr.%20Roman%20Bartnik> . 
- Der Fokus der neueren Kurse liegt auf der **Anpassung von Prüfungsleistungen und Gruppenarbeiten** an die neuen technischen Möglichkeiten. - Ein neuer Kurs im Mai 2026 thematisiert auch, wie man mit GenAI solche **interaktiven Skripte erstellt**.

